version: '3.1'

services:
  db:
    image: postgres:13.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  ocp-skills-api:
    build: .
    restart: unless-stopped
    links:
      - db
    ports:
      - "8000:82"