// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: api/ocp-skill-api/ocp-skill-api.proto

package ocp_skill_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSkillRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateSkillRequestV1) Reset() {
	*x = CreateSkillRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSkillRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequestV1) ProtoMessage() {}

func (x *CreateSkillRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequestV1.ProtoReflect.Descriptor instead.
func (*CreateSkillRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSkillRequestV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSkillRequestV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSkillResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSkillResponseV1) Reset() {
	*x = CreateSkillResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSkillResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillResponseV1) ProtoMessage() {}

func (x *CreateSkillResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillResponseV1.ProtoReflect.Descriptor instead.
func (*CreateSkillResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkillResponseV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeSkillRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DescribeSkillRequestV1) Reset() {
	*x = DescribeSkillRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeSkillRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSkillRequestV1) ProtoMessage() {}

func (x *DescribeSkillRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSkillRequestV1.ProtoReflect.Descriptor instead.
func (*DescribeSkillRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeSkillRequestV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeSkillResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skill *Skill `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
}

func (x *DescribeSkillResponseV1) Reset() {
	*x = DescribeSkillResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeSkillResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSkillResponseV1) ProtoMessage() {}

func (x *DescribeSkillResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSkillResponseV1.ProtoReflect.Descriptor instead.
func (*DescribeSkillResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeSkillResponseV1) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type ListSkillsRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListSkillsRequestV1) Reset() {
	*x = ListSkillsRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillsRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequestV1) ProtoMessage() {}

func (x *ListSkillsRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequestV1.ProtoReflect.Descriptor instead.
func (*ListSkillsRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListSkillsRequestV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListSkillsRequestV1) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSkillsRequestV1) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSkillsResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skills []*Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
}

func (x *ListSkillsResponseV1) Reset() {
	*x = ListSkillsResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkillsResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponseV1) ProtoMessage() {}

func (x *ListSkillsResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponseV1.ProtoReflect.Descriptor instead.
func (*ListSkillsResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListSkillsResponseV1) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type RemoveSkillRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveSkillRequestV1) Reset() {
	*x = RemoveSkillRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSkillRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkillRequestV1) ProtoMessage() {}

func (x *RemoveSkillRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkillRequestV1.ProtoReflect.Descriptor instead.
func (*RemoveSkillRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveSkillRequestV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveSkillResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveSkillResponseV1) Reset() {
	*x = RemoveSkillResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSkillResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkillResponseV1) ProtoMessage() {}

func (x *RemoveSkillResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkillResponseV1.ProtoReflect.Descriptor instead.
func (*RemoveSkillResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveSkillResponseV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

//Skill model properties
type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Skill) Reset() {
	*x = Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP(), []int{8}
}

func (x *Skill) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Skill) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_ocp_skill_api_ocp_skill_api_proto protoreflect.FileDescriptor

var file_api_ocp_skill_api_ocp_skill_api_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2d, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x17,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x22, 0x5c, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x44, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x27, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x05, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xe7,
	0x03, 0x0a, 0x0b, 0x4f, 0x63, 0x70, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x41, 0x70, 0x69, 0x12, 0x75,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x56, 0x31, 0x12, 0x22,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x56, 0x31, 0x1a, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12,
	0x14, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2f, 0x7b, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x71, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x24, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56,
	0x31, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x79, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x56, 0x31, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x73, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x24, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22,
	0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x2a, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63,
	0x70, 0x2d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x6f, 0x63, 0x70, 0x2d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x63,
	0x70, 0x5f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_skill_api_ocp_skill_api_proto_rawDescOnce sync.Once
	file_api_ocp_skill_api_ocp_skill_api_proto_rawDescData = file_api_ocp_skill_api_ocp_skill_api_proto_rawDesc
)

func file_api_ocp_skill_api_ocp_skill_api_proto_rawDescGZIP() []byte {
	file_api_ocp_skill_api_ocp_skill_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_skill_api_ocp_skill_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_skill_api_ocp_skill_api_proto_rawDescData)
	})
	return file_api_ocp_skill_api_ocp_skill_api_proto_rawDescData
}

var file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ocp_skill_api_ocp_skill_api_proto_goTypes = []interface{}{
	(*CreateSkillRequestV1)(nil),    // 0: ocp.skill.api.CreateSkillRequestV1
	(*CreateSkillResponseV1)(nil),   // 1: ocp.skill.api.CreateSkillResponseV1
	(*DescribeSkillRequestV1)(nil),  // 2: ocp.skill.api.DescribeSkillRequestV1
	(*DescribeSkillResponseV1)(nil), // 3: ocp.skill.api.DescribeSkillResponseV1
	(*ListSkillsRequestV1)(nil),     // 4: ocp.skill.api.ListSkillsRequestV1
	(*ListSkillsResponseV1)(nil),    // 5: ocp.skill.api.ListSkillsResponseV1
	(*RemoveSkillRequestV1)(nil),    // 6: ocp.skill.api.RemoveSkillRequestV1
	(*RemoveSkillResponseV1)(nil),   // 7: ocp.skill.api.RemoveSkillResponseV1
	(*Skill)(nil),                   // 8: ocp.skill.api.Skill
}
var file_api_ocp_skill_api_ocp_skill_api_proto_depIdxs = []int32{
	8, // 0: ocp.skill.api.DescribeSkillResponseV1.skill:type_name -> ocp.skill.api.Skill
	8, // 1: ocp.skill.api.ListSkillsResponseV1.skills:type_name -> ocp.skill.api.Skill
	4, // 2: ocp.skill.api.OcpSkillApi.ListSkillsV1:input_type -> ocp.skill.api.ListSkillsRequestV1
	0, // 3: ocp.skill.api.OcpSkillApi.CreateSkillV1:input_type -> ocp.skill.api.CreateSkillRequestV1
	2, // 4: ocp.skill.api.OcpSkillApi.DescribeSkillV1:input_type -> ocp.skill.api.DescribeSkillRequestV1
	6, // 5: ocp.skill.api.OcpSkillApi.RemoveSkillV1:input_type -> ocp.skill.api.RemoveSkillRequestV1
	5, // 6: ocp.skill.api.OcpSkillApi.ListSkillsV1:output_type -> ocp.skill.api.ListSkillsResponseV1
	1, // 7: ocp.skill.api.OcpSkillApi.CreateSkillV1:output_type -> ocp.skill.api.CreateSkillResponseV1
	3, // 8: ocp.skill.api.OcpSkillApi.DescribeSkillV1:output_type -> ocp.skill.api.DescribeSkillResponseV1
	7, // 9: ocp.skill.api.OcpSkillApi.RemoveSkillV1:output_type -> ocp.skill.api.RemoveSkillResponseV1
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ocp_skill_api_ocp_skill_api_proto_init() }
func file_api_ocp_skill_api_ocp_skill_api_proto_init() {
	if File_api_ocp_skill_api_ocp_skill_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSkillRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSkillResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeSkillRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeSkillResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillsRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkillsResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSkillRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSkillResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_skill_api_ocp_skill_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_skill_api_ocp_skill_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_skill_api_ocp_skill_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_skill_api_ocp_skill_api_proto_msgTypes,
	}.Build()
	File_api_ocp_skill_api_ocp_skill_api_proto = out.File
	file_api_ocp_skill_api_ocp_skill_api_proto_rawDesc = nil
	file_api_ocp_skill_api_ocp_skill_api_proto_goTypes = nil
	file_api_ocp_skill_api_ocp_skill_api_proto_depIdxs = nil
}
